# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siirler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muzik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_adi', models.CharField(max_length=31)),
                ('in_bestecisi', models.CharField(blank=True, max_length=31)),
                ('in_icracisi', models.CharField(blank=True, max_length=31)),
                ('in_linki', models.URLField(blank=True, max_length=255)),
                ('in_yeri', models.URLField(blank=True, max_length=255)),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=31, unique=True)),
            ],
            options={
                'ordering': ['in_adi'],
            },
        ),
        migrations.CreateModel(
            name='Okuma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_muzik_basi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='muzikin_basi')),
                ('in_muzik_sonu', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='muzikin_sonu')),
                ('in_toplam_saniyesi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='toplam(sn)')),
                ('in_tarihi', models.DateField(blank=True, verbose_name='okuma_tarihi')),
                ('in_yeri', models.URLField(blank=True, max_length=255)),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=31, unique=True)),
                ('in_muziki', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='okumalar.Muzik')),
                ('in_siiri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siirler.Siir')),
            ],
            options={
                'get_latest_by': 'in_tarihi',
                'ordering': ['in_siiri'],
            },
        ),
    ]
