# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okumalar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muzik',
            options={'ordering': ['in_adi'], 'verbose_name': 'Müzik', 'verbose_name_plural': 'MÜZİKLER'},
        ),
        migrations.AlterModelOptions(
            name='okuma',
            options={'get_latest_by': 'in_tarihi', 'ordering': ['in_siiri'], 'verbose_name': 'Okuma', 'verbose_name_plural': 'OKUMALAR'},
        ),
        migrations.AlterField(
            model_name='muzik',
            name='slug',
            field=models.SlugField(blank=True, help_text='A label for URL config.', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='okuma',
            name='in_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='okuma_tarihi'),
        ),
        migrations.AlterField(
            model_name='okuma',
            name='slug',
            field=models.SlugField(blank=True, help_text='A label for URL config.', max_length=31, null=True),
        ),
    ]
