# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_adi', models.CharField(max_length=63)),
                ('in_yazari', models.CharField(blank=True, max_length=63)),
                ('in_basim_senesi', models.IntegerField(blank=True, verbose_name='kitabin_tarihi')),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=31, unique=True)),
            ],
            options={
                'get_latest_by': 'in_basim_senesi',
                'verbose_name': 'kitap adi',
                'ordering': ['-in_yazari'],
            },
        ),
        migrations.CreateModel(
            name='Sair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_adi', models.CharField(db_index=True, max_length=31)),
                ('in_dogumu', models.IntegerField(blank=True, verbose_name='sairin_dogum_senesi')),
                ('in_vefati', models.IntegerField(blank=True, verbose_name='sairin_vefat_senesi')),
                ('websitesi', models.URLField(blank=True, max_length=255)),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=31, unique=True)),
            ],
            options={
                'ordering': ['in_adi'],
            },
        ),
        migrations.CreateModel(
            name='Siir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_adi', models.CharField(max_length=31, unique=True)),
                ('in_kendi', models.TextField(blank=True)),
                ('in_tarihi', models.IntegerField(blank=True, verbose_name='siirin_tarihi')),
                ('slug', models.SlugField(default='', help_text='A label for URL config.', max_length=31, unique=True)),
                ('in_kitabi', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='siirler.Kitap')),
                ('in_sairi', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='siirler.Sair')),
            ],
            options={
                'ordering': ['in_sairi'],
            },
        ),
    ]
