# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siirler', '0002_auto_20170527_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sair',
            name='in_dogumu',
            field=models.IntegerField(blank=True, null=True, verbose_name='sairin-dogum-senesi'),
        ),
        migrations.AlterField(
            model_name='sair',
            name='in_vefati',
            field=models.IntegerField(blank=True, null=True, verbose_name='sairin-vefat-senesi'),
        ),
    ]
