# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siirler', '0003_auto_20170527_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sair',
            name='in_dogumu',
            field=models.IntegerField(blank=True, null=True, verbose_name='sairin_dogum_senesi'),
        ),
        migrations.AlterField(
            model_name='sair',
            name='in_vefati',
            field=models.IntegerField(blank=True, null=True, verbose_name='sairin_vefat_senesi'),
        ),
    ]
