# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siirler', '0006_auto_20170527_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='slug',
            field=models.SlugField(blank=True, help_text='A label for URL config.', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='sair',
            name='slug',
            field=models.SlugField(blank=True, help_text='A label for URL config.', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='siir',
            name='slug',
            field=models.SlugField(blank=True, help_text='A label for URL config.', max_length=31, null=True),
        ),
    ]
