# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siirler', '0013_auto_20170527_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siir',
            options={'ordering': ['in_sairi'], 'verbose_name': 'Siir', 'verbose_name_plural': 'Siir'},
        ),
    ]
