# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siirler', '0014_auto_20170528_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siir',
            options={'ordering': ['in_sairi'], 'verbose_name': 'ŞİİR', 'verbose_name_plural': 'ŞİİR'},
        ),
        migrations.AddField(
            model_name='siir',
            name='in_kaydi',
            field=models.FileField(blank=True, null=True, upload_to='kayitlar'),
        ),
    ]
