# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siirler', '0015_auto_20170607_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siir',
            name='in_kaydi',
            field=models.FileField(blank=True, null=True, upload_to='siirler/static/kayitlar/'),
        ),
    ]
