# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siirler', '0020_auto_20170608_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siir',
            name='in_kaydi',
            field=models.FileField(blank=True, null=True, upload_to='kayitlar/'),
        ),
    ]
